name: lab_4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: any
  path_provider: any
  shared_preferences: any
  hive: any
  hive_flutter: any
  build_runner: any
  permission_handler: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  hive_generator: any 

flutter:
  uses-material-design: true
